version: '3.7'

services:
  mi-es:
    image: "elasticsearch:7.8.0"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9269:9200"
      - "9369:9300"
volumes:
  mi-elasticsearch:
