version: '3.7'
# 以下配置仅为测试使用,勿至生产环境使用

services:
  mi-nginx:
    image: nginx:alpine
    restart: always
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - mi-network
    ports:
      - "8081:80"
    volumes:
      - "./:/opt/www"
      - "./docker/nginx/laravel-es.conf:/etc/nginx/conf.d/laravel-es.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
  mi-php:
    container_name: mi-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    tty: true
    networks:
      - mi-network
    ports:
      - "86:80"
    volumes:
      - "./:/opt/www"
  mi-es:
    image: "elasticsearch:7.8.0"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - mi-network
    ports:
      - "9269:9200"
      - "9369:9300"
    volumes:
      - "./docker/elasticsearch/plugins/ik:/usr/share/elasticsearch/plugins/ik"
  mi-kibana:
    image: "kibana:7.8.0"
    ports:
      - "5661:5601"
    networks:
      - mi-network
    volumes:
      - type: bind
        source: ./docker/kibana/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
      - mi-es
volumes:
  mi-elasticsearch:

networks:
  mi-network:
